/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface EncryptedVotingInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "castVote"
      | "finalize"
      | "isValidVote"
      | "proposal"
      | "totalVotes"
      | "voteIsValid"
      | "winning"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "castVote",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "finalize", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "isValidVote",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "proposal", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "totalVotes",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "voteIsValid",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "winning", values?: undefined): string;

  decodeFunctionResult(functionFragment: "castVote", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "finalize", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isValidVote",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "proposal", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "totalVotes", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "voteIsValid",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "winning", data: BytesLike): Result;
}

export interface EncryptedVoting extends BaseContract {
  connect(runner?: ContractRunner | null): EncryptedVoting;
  waitForDeployment(): Promise<this>;

  interface: EncryptedVotingInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  castVote: TypedContractMethod<
    [inputEuintVote: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  finalize: TypedContractMethod<[], [void], "nonpayable">;

  isValidVote: TypedContractMethod<
    [inputEuintVote: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  proposal: TypedContractMethod<[], [string], "view">;

  totalVotes: TypedContractMethod<[], [bigint], "view">;

  voteIsValid: TypedContractMethod<[], [string], "view">;

  winning: TypedContractMethod<[], [[string, string]], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "castVote"
  ): TypedContractMethod<
    [inputEuintVote: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "finalize"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "isValidVote"
  ): TypedContractMethod<
    [inputEuintVote: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "proposal"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "totalVotes"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "voteIsValid"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "winning"
  ): TypedContractMethod<[], [[string, string]], "view">;

  filters: {};
}
