/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as simpleSol from "./Simple.sol";
export type { simpleSol };
export type { EncryptedVoting } from "./EncryptedVoting";
export type { FHECounter } from "./FHECounter";
