/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface TestInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "encryptedSimpleValue"
      | "encryptedSum"
      | "storeEncryptedSimpleValue"
      | "storeEncryptedSum"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "encryptedSimpleValue",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "encryptedSum",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "storeEncryptedSimpleValue",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "storeEncryptedSum",
    values: [BytesLike, BytesLike, BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "encryptedSimpleValue",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "encryptedSum",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "storeEncryptedSimpleValue",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "storeEncryptedSum",
    data: BytesLike
  ): Result;
}

export interface Test extends BaseContract {
  connect(runner?: ContractRunner | null): Test;
  waitForDeployment(): Promise<this>;

  interface: TestInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  encryptedSimpleValue: TypedContractMethod<[], [string], "view">;

  encryptedSum: TypedContractMethod<[], [string], "view">;

  storeEncryptedSimpleValue: TypedContractMethod<
    [input: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  storeEncryptedSum: TypedContractMethod<
    [input1: BytesLike, input2: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "encryptedSimpleValue"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "encryptedSum"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "storeEncryptedSimpleValue"
  ): TypedContractMethod<
    [input: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "storeEncryptedSum"
  ): TypedContractMethod<
    [input1: BytesLike, input2: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  filters: {};
}
